export const DEFINiTIONS = [
  "Account means a unique account created for You to access our Service or parts of our Service",
  "Cookies are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses",
  "Country refers to: Washington, United States",
  "Device means any device that can access the Service such as a computer, a cellphone or a digital tablet",
  "Personal Data is any information that relates to an identified or identifiable individual",
  "Service refers to the Website",
  "Service Provider means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used",
  "Usage Data refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit)",
  "You means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable",
];

export const PERSONAL_DATA = [
  "Email address",
  "First name and last name",
  "Phone number",
  "Usage Data",
];
